export const products = ["Nike", "Adidas", "Air Jordan", "Puma", "Umbro", "Joma", "New Balance", "Reebok"];
export const menus = [
  { id: 1, name: "Home", url: "/" },
  { id: 2, name: "About us", url: "/about" },
  { id: 3, name: "List Cars", url: "/cars" },
];
export const typeCar = [
  "Convertible",
  "Extended Cab Pickup",
  "Regular Cab Pickup",
  "Minivan",
  "Crew Cab Pickup",
  "Coupe",
  "Passenger Van",
  "Wagon",
  "SUV",
  "MPV",
  "Hatchback",
  "Sedan",
  "Sport",
  "Crossover",
  "Electric",
  "Off Road",
];
export const carOptions = [
  "Alarm",
  "AM/FM Stereo",
  "Airbag: Passenger",
  "Airbag: Driver",
  "Airbag: Side",
  "Antilock Brakes",
  "A/C: Rear",
  "A/C: Front",
  "Alloy Wheels",
  "Bucket Seats",
  "Cassette Player",
  "Cruise Control",
  "CD (Single Disc)",
  "CD (Multi Disc)",
  "Fog Lights",
  "Integrated Phone",
  "Keyless Entry",
  "Memory Seats",
  "MP3 (Single Disc)",
  "Navigation",
  "Rear Window Defroster",
  "Power Windows",
  "Power Steering",
  "Power Seats",
  "Premium Sound",
  "Tinted Glass",
  "Third Row Seats",
];

export const carSpecs = [
  "Brake assist",
  "Leather-wrapped shift knob",
  "Glove box lamp",
  "Rear passenger map pockets",
  "Electrochromic rearview mirror",
  "Dual chrome exhaust tips",
  "Direct-type tire pressure monitor system",
  "Cargo area lamp",
  "Automatic temperature control",
  "Electronic stability",
  "Trip computer",
  "Power steering",
  "Power door mirrors",
  "Front bucket seats",
  "Navigation system",
  "Wireless phone connectivity",
  "Power driver seat",
  "Rear window defroster",
  "Front bucket seats",
  "Rear window defroster",
  "Exterior parking camera rear",
  "Front dual zone A/C",
];
